### PR TITLE
Added wireframes

### PR DESCRIPTION
**Pull request by GeorgeiGoncharik**

### CODE REVIEW

**Review by gmltA — CHANGES_REQUESTED** [review]
Seems like you forgot to put HTML tags on your wireframes.

**Comment by GeorgeiGoncharik** [comment]
> Seems like you forgot to put HTML tags on your wireframes.

I inadvertently misled you, because I only added tags to the wireframes.png files in each directory.

**Review by gmltA — CHANGES_REQUESTED** [review]
Ah, I see. Sorry, but wireframes are not detailed enough. Add more detailed markup please.

**Comment by GeorgeiGoncharik** [comment]
> Ah, I see. Sorry, but wireframes are not detailed enough. Add more detailed markup please.

done

**Comment by GeorgeiGoncharik** [comment]
> Ah, I see. Sorry, but wireframes are not detailed enough. Add more detailed markup please.

Attention

HTML теги расписал только в мобильной версии т.к. они идентичны десктопной версии

**Review by gmltA — COMMENTED** [review]
Elements that are meant to change document location (such as links to sign in pages) must be wrapped in `<a>` tags.

After you fix these, I can offer you <kbd>7</kbd>.

**Review by gmltA — APPROVED** [review]

**Pull request merged**
